import React, { useState } from 'react'
import PropTypes from 'prop-types'
import Link from 'next/link'
import Head from 'next/head'
import {signIn, signOut,useSession} from 'next-auth/react'

function Home() {
  const {data: session, status} = useSession()
  const loading=status

  // const loading=status === 'loading'
  console.log({session, status})
  const user = process.env.DB_USER
  console.log(user)
  return (
    <>
    <Head>
      <title>Hello</title>
      <meta name="desc" content='generated by me'/>
    </Head>
    <h1>Home Page</h1>

    {/* {!loading && !session &&( */}

    { !session &&(
    <Link href='/api/auth/signin' 
      onClick={(e) => {
      e.preventDefault()
      signIn('github')
    }}>SignIn with github</Link>
    )}
    <br/>
    {session && (
    <Link href='/api/auth/signout' 
      onClick={(e) => {
      e.preventDefault()
      signOut()
    }}>Sign Out</Link>
    )}<br/>
    <Link href='/users'>Users Page</Link>
    </>
  )
}

export default Home
